### DISCUSSION TITLE
I want multi-line truncation via CSS

### DISCUSSION THREAD

**Discussion by aarongustafson** [WebWeWant/webwewant.fyi#27] [Wants]
Single-line text truncation is easy, straightforward, and broadly supported in browsers; however, multi-line text truncation requires JavaScript, half-baked and non-standardized CSS properties, or fragile hacks to accomplish.

The closest attempt I've seen is the `-webkit-line-clamp` approach:

```css
.line-clamp {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;  
}
```

<hr>

https://webwewant.fyi/wants/5e59460efa695ea9f7750152/
