### ISSUE TITLE
I want auto resizing text-area

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#214]
I want to be able to tell a text area that it has to expand vertically (or horizontally) to fit its content.

Maybe something like this?

```css
textarea {
  resize: vertical-auto;
}
```

<hr>

https://webwewant.fyi/wants/130/
