### ISSUE TITLE
Should we add related specs/proposals/explainers to want front matter?

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#31]
I feel like it could be useful. Perhaps something like this?

```yml
related:
  - title: Name of the document
    url: https://domain.tld/path/to/document
    type: explainer
  - title: Name of the document
    url: https://domain.tld/path/to/document
    type: spec
```

This could make it easier to connect it to related stuff. We could standardize on a few types to begin with:

* explainer - for early ideas
* draft - working draft, editor’s draft, etc.
* spec - recommendation (likely only included if uptake is low)
* note - if there’s a related Note that’s been published
* discussion - GitHub, WICG, or mailing list discussions

Would this cover enough things to begin with? How should we indicate if something has been abandoned? Notes are often the dead end as I understand it. CSS Regions is a good example of an abandoned WD though.
