### ISSUE TITLE
I want `@keyframes` to support seconds as indicator for a keyframe

### ISSUE THREAD

**Issue by aarongustafson** [WebWeWant/webwewant.fyi#97]
I&#39;m just starting with `@keyframes` for a bit, but with animations, timing is sometimes very precise and critical. From what I see, you can only use &#39;from&#39; and &#39;to&#39; or use percentages, so to get some timings right can be pretty hard.

Ideally, I&#39;d like to have the control to precisely add a keyframe via a timestamp in seconds. 

Something like this:

```css
@keyframes demo {
  1s {
    color: #f00;
  }
  1.5s {
    color: #0f0;
  }
  1.75s {
    color: #00f;
  }
}
```

Obviously, the `animation-duration` property should match the length of the keyframes somehow (either explicitly or implicitly).

<hr>

https://webwewant.fyi/wants/87/
